spring.application.name=ticketing

## Database SQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgredb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

## Database NoSQL
# application-local.properties
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=psp_integrator
spring.mongodb.username=noverryjs
spring.mongodb.password=Sorosutan@54
spring.mongodb.authentication-database=psp_integrator

#spring.mongodb.uri=mongodb://noverryjs:Sorosutan%4054@localhost:27017/psp_integrator?authSource=psp_integrator

# Connection pool settings
spring.data.mongodb.connections-per-host=100
spring.data.mongodb.min-connections-per-host=10
spring.data.mongodb.threads-allowed-to-block-for-connection-multiplier=5

# Timeout settings
spring.data.mongodb.connect-timeout=30000
spring.data.mongodb.socket-timeout=30000
spring.data.mongodb.server-selection-timeout=30000


application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Enable/disable sensitive data masking
logging.sensitive.enabled=true
logging.sensitive.fields=password,pwd,token,secret,apikey,accesstoken,refreshtoken,pin,cvv,cardnumber
logging.sensitive.mask-with=******
logging.sensitive.patterns=(?i)(\"password\"\\s*:\\s*\")([^\"]*)(\"),(?i)(password=)([^&\\s]*),(?i)(\"token\"\\s*:\\s*\")([^\"]*)(\")

audit.enabled=${AUDIT_ENABLED:false}
audit.collection=audit_logs
audit.retention-days=90
#
#logging.level.co.apps.ticketing.service.MaskingService=DEBUG
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#redis
spring.data.redis.host=${REDIS_URL:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:55000}
spring.cache.type=redis
spring.cache.redis.time-to-live=${REDIS_TTL:30m}
spring.cache.redis.cache-null-values=false